const validImages = [
	// images for spots. get a lot more to function as preview
	{
		type: "spot",
		typeId: 1,
		url: "https://kblairbnb.s3.us-west-1.amazonaws.com/spot/1-0.jpg",
		previewImg: false,
		userId: 1,
	},
	{
		type: "spot",
		typeId: 1,
		url: "https://kblairbnb.s3.us-west-1.amazonaws.com/spot/1-1.jpg",
		previewImg: false,
		userId: 1,
	},
	{
		type: "spot",
		typeId: 1,
		url: "https://kblairbnb.s3.us-west-1.amazonaws.com/spot/1-2.jpg",
		previewImg: false,
		userId: 1,
	},
	{
		type: "spot",
		typeId: 1,
		url: "https://kblairbnb.s3.us-west-1.amazonaws.com/spot/1-3.jpg",
		previewImg: false,
		userId: 1,
	},
	{
		type: "spot",
		typeId: 1,
		url: "https://kblairbnb.s3.us-west-1.amazonaws.com/spot/1-4.jpg",
		previewImg: false,
		userId: 1,
	},

	{
		type: "spot",
		typeId: 2,
		url: "https://kblairbnb.s3.us-west-1.amazonaws.com/spot/2-0.jpg",
		previewImg: false,
		userId: 2,
	},
	{
		type: "spot",
		typeId: 2,
		url: "https://kblairbnb.s3.us-west-1.amazonaws.com/spot/2-1.jpg",
		previewImg: false,
		userId: 2,
	},
	{
		type: "spot",
		typeId: 2,
		url: "https://kblairbnb.s3.us-west-1.amazonaws.com/spot/2-2.jpg",
		previewImg: false,
		userId: 2,
	},
	{
		type: "spot",
		typeId: 2,
		url: "https://kblairbnb.s3.us-west-1.amazonaws.com/spot/2-3.jpg",
		previewImg: false,
		userId: 2,
	},
	{
		type: "spot",
		typeId: 2,
		url: "https://kblairbnb.s3.us-west-1.amazonaws.com/spot/2-4.jpg",
		previewImg: false,
		userId: 2,
	},
	{
		type: "spot",
		typeId: 2,
		url: "https://kblairbnb.s3.us-west-1.amazonaws.com/spot/2-5.jpg",
		previewImg: false,
		userId: 2,
	},

	{
		type: "spot",
		typeId: 3,
		url: "https://kblairbnb.s3.us-west-1.amazonaws.com/spot/3-0.jpg",
		previewImg: false,
		userId: 3,
	},
	{
		type: "spot",
		typeId: 3,
		url: "https://kblairbnb.s3.us-west-1.amazonaws.com/spot/3-1.jpg",
		previewImg: false,
		userId: 3,
	},
	{
		type: "spot",
		typeId: 3,
		url: "https://kblairbnb.s3.us-west-1.amazonaws.com/spot/3-2.jpg",
		previewImg: false,
		userId: 3,
	},
	{
		type: "spot",
		typeId: 3,
		url: "https://kblairbnb.s3.us-west-1.amazonaws.com/spot/3-3.jpg",
		previewImg: false,
		userId: 3,
	},
	{
		type: "spot",
		typeId: 3,
		url: "https://kblairbnb.s3.us-west-1.amazonaws.com/spot/3-4.jpg",
		previewImg: false,
		userId: 3,
	},
	{
		type: "spot",
		typeId: 3,
		url: "https://kblairbnb.s3.us-west-1.amazonaws.com/spot/3-5.jpg",
		previewImg: false,
		userId: 3,
	},
	{
		type: "spot",
		typeId: 3,
		url: "https://kblairbnb.s3.us-west-1.amazonaws.com/spot/3-6.jpg",
		previewImg: false,
		userId: 3,
	},

	{
		type: "spot",
		typeId: 4,
		url: "https://kblairbnb.s3.us-west-1.amazonaws.com/spot/4-0.jpg",
		previewImg: false,
		userId: 1,
	},
	{
		type: "spot",
		typeId: 4,
		url: "https://kblairbnb.s3.us-west-1.amazonaws.com/spot/4-1.jpg",
		previewImg: false,
		userId: 1,
	},
	{
		type: "spot",
		typeId: 4,
		url: "https://kblairbnb.s3.us-west-1.amazonaws.com/spot/4-2.jpg",
		previewImg: false,
		userId: 1,
	},
	{
		type: "spot",
		typeId: 4,
		url: "https://kblairbnb.s3.us-west-1.amazonaws.com/spot/4-3.jpg",
		previewImg: false,
		userId: 1,
	},
	{
		type: "spot",
		typeId: 4,
		url: "https://kblairbnb.s3.us-west-1.amazonaws.com/spot/4-4.jpg",
		previewImg: false,
		userId: 1,
	},

	{
		type: "spot",
		typeId: 5,
		url: "https://kblairbnb.s3.us-west-1.amazonaws.com/spot/5-0.jpg",
		previewImg: false,
		userId: 2,
	},
	{
		type: "spot",
		typeId: 5,
		url: "https://kblairbnb.s3.us-west-1.amazonaws.com/spot/5-1.jpg",
		previewImg: false,
		userId: 2,
	},
	{
		type: "spot",
		typeId: 5,
		url: "https://kblairbnb.s3.us-west-1.amazonaws.com/spot/5-2.jpg",
		previewImg: false,
		userId: 2,
	},
	{
		type: "spot",
		typeId: 5,
		url: "https://kblairbnb.s3.us-west-1.amazonaws.com/spot/5-3.jpg",
		previewImg: false,
		userId: 2,
	},

	{
		type: "spot",
		typeId: 6,
		url: "https://kblairbnb.s3.us-west-1.amazonaws.com/spot/6-0.jpg",
		previewImg: false,
		userId: 3,
	},
	{
		type: "spot",
		typeId: 6,
		url: "https://kblairbnb.s3.us-west-1.amazonaws.com/spot/6-1.jpg",
		previewImg: false,
		userId: 3,
	},
	{
		type: "spot",
		typeId: 6,
		url: "https://kblairbnb.s3.us-west-1.amazonaws.com/spot/6-2.jpg",
		previewImg: false,
		userId: 3,
	},
	{
		type: "spot",
		typeId: 6,
		url: "https://kblairbnb.s3.us-west-1.amazonaws.com/spot/6-3.jpg",
		previewImg: false,
		userId: 3,
	},
	{
		type: "spot",
		typeId: 6,
		url: "https://kblairbnb.s3.us-west-1.amazonaws.com/spot/6-4.jpg",
		previewImg: false,
		userId: 3,
	},
	{
		type: "spot",
		typeId: 6,
		url: "https://kblairbnb.s3.us-west-1.amazonaws.com/spot/6-5.jpg",
		previewImg: false,
		userId: 3,
	},
	{
		type: "spot",
		typeId: 6,
		url: "https://kblairbnb.s3.us-west-1.amazonaws.com/spot/6-6.jpg",
		previewImg: false,
		userId: 3,
	},
	{
		type: "spot",
		typeId: 6,
		url: "https://kblairbnb.s3.us-west-1.amazonaws.com/spot/6-7.jpg",
		previewImg: false,
		userId: 3,
	},
	{
		type: "spot",
		typeId: 6,
		url: "https://kblairbnb.s3.us-west-1.amazonaws.com/spot/6-8.jpg",
		previewImg: false,
		userId: 3,
	},

	{
		type: "spot",
		typeId: 7,
		url: "https://kblairbnb.s3.us-west-1.amazonaws.com/spot/7-0.jpg",
		previewImg: false,
		userId: 1,
	},
	{
		type: "spot",
		typeId: 7,
		url: "https://kblairbnb.s3.us-west-1.amazonaws.com/spot/7-1.jpg",
		previewImg: false,
		userId: 1,
	},
	{
		type: "spot",
		typeId: 7,
		url: "https://kblairbnb.s3.us-west-1.amazonaws.com/spot/7-2.jpg",
		previewImg: false,
		userId: 1,
	},

	{
		type: "spot",
		typeId: 8,
		url: "https://kblairbnb.s3.us-west-1.amazonaws.com/spot/8-0.jpg",
		previewImg: false,
		userId: 2,
	},
	{
		type: "spot",
		typeId: 8,
		url: "https://kblairbnb.s3.us-west-1.amazonaws.com/spot/8-1.jpg",
		previewImg: false,
		userId: 2,
	},
	{
		type: "spot",
		typeId: 8,
		url: "https://kblairbnb.s3.us-west-1.amazonaws.com/spot/8-2.jpg",
		previewImg: false,
		userId: 2,
	},
	{
		type: "spot",
		typeId: 8,
		url: "https://kblairbnb.s3.us-west-1.amazonaws.com/spot/8-3.jpg",
		previewImg: false,
		userId: 2,
	},
	{
		type: "spot",
		typeId: 8,
		url: "https://kblairbnb.s3.us-west-1.amazonaws.com/spot/8-4.jpg",
		previewImg: false,
		userId: 2,
	},

	{
		type: "spot",
		typeId: 9,
		url: "https://kblairbnb.s3.us-west-1.amazonaws.com/spot/9-0.jpg",
		previewImg: false,
		userId: 3,
	},
	{
		type: "spot",
		typeId: 9,
		url: "https://kblairbnb.s3.us-west-1.amazonaws.com/spot/9-1.jpg",
		previewImg: false,
		userId: 3,
	},
	{
		type: "spot",
		typeId: 9,
		url: "https://kblairbnb.s3.us-west-1.amazonaws.com/spot/9-2.jpg",
		previewImg: false,
		userId: 3,
	},
	{
		type: "spot",
		typeId: 9,
		url: "https://kblairbnb.s3.us-west-1.amazonaws.com/spot/9-3.jpg",
		previewImg: false,
		userId: 3,
	},
	{
		type: "spot",
		typeId: 9,
		url: "https://kblairbnb.s3.us-west-1.amazonaws.com/spot/9-4.jpg",
		previewImg: false,
		userId: 3,
	},
	{
		type: "spot",
		typeId: 9,
		url: "https://kblairbnb.s3.us-west-1.amazonaws.com/spot/9-5.jpg",
		previewImg: false,
		userId: 3,
	},
	{
		type: "spot",
		typeId: 9,
		url: "https://kblairbnb.s3.us-west-1.amazonaws.com/spot/9-6.jpg",
		previewImg: false,
		userId: 3,
	},
	{
		type: "spot",
		typeId: 9,
		url: "https://kblairbnb.s3.us-west-1.amazonaws.com/spot/9-7.jpg",
		previewImg: false,
		userId: 3,
	},
	{
		type: "spot",
		typeId: 9,
		url: "https://kblairbnb.s3.us-west-1.amazonaws.com/spot/9-8.jpg",
		previewImg: false,
		userId: 3,
	},

	{
		type: "spot",
		typeId: 10,
		url: "https://kblairbnb.s3.us-west-1.amazonaws.com/spot/10-0.jpg",
		previewImg: false,
		userId: 1,
	},
	{
		type: "spot",
		typeId: 10,
		url: "https://kblairbnb.s3.us-west-1.amazonaws.com/spot/10-1.jpg",
		previewImg: false,
		userId: 1,
	},
	{
		type: "spot",
		typeId: 10,
		url: "https://kblairbnb.s3.us-west-1.amazonaws.com/spot/10-2.jpg",
		previewImg: false,
		userId: 1,
	},
	{
		type: "spot",
		typeId: 10,
		url: "https://kblairbnb.s3.us-west-1.amazonaws.com/spot/10-3.jpg",
		previewImg: false,
		userId: 1,
	},
	{
		type: "spot",
		typeId: 10,
		url: "https://kblairbnb.s3.us-west-1.amazonaws.com/spot/10-4.jpg",
		previewImg: false,
		userId: 1,
	},

	{
		type: "spot",
		typeId: 11,
		url: "https://kblairbnb.s3.us-west-1.amazonaws.com/spot/11-0.jpg",
		previewImg: false,
		userId: 2,
	},
	{
		type: "spot",
		typeId: 11,
		url: "https://kblairbnb.s3.us-west-1.amazonaws.com/spot/11-1.jpg",
		previewImg: false,
		userId: 2,
	},
	{
		type: "spot",
		typeId: 11,
		url: "https://kblairbnb.s3.us-west-1.amazonaws.com/spot/11-2.jpg",
		previewImg: false,
		userId: 2,
	},
	{
		type: "spot",
		typeId: 11,
		url: "https://kblairbnb.s3.us-west-1.amazonaws.com/spot/11-3.jpg",
		previewImg: false,
		userId: 2,
	},
	{
		type: "spot",
		typeId: 11,
		url: "https://kblairbnb.s3.us-west-1.amazonaws.com/spot/11-4.jpg",
		previewImg: false,
		userId: 2,
	},

	{
		type: "spot",
		typeId: 12,
		url: "https://kblairbnb.s3.us-west-1.amazonaws.com/spot/12-0.jpg",
		previewImg: false,
		userId: 5,
	},
	{
		type: "spot",
		typeId: 12,
		url: "https://kblairbnb.s3.us-west-1.amazonaws.com/spot/12-1.jpg",
		previewImg: false,
		userId: 5,
	},
	{
		type: "spot",
		typeId: 12,
		url: "https://kblairbnb.s3.us-west-1.amazonaws.com/spot/12-2.jpg",
		previewImg: false,
		userId: 5,
	},
	{
		type: "spot",
		typeId: 12,
		url: "https://kblairbnb.s3.us-west-1.amazonaws.com/spot/12-3.jpg",
		previewImg: false,
		userId: 5,
	},
	{
		type: "spot",
		typeId: 12,
		url: "https://kblairbnb.s3.us-west-1.amazonaws.com/spot/12-4.jpg",
		previewImg: false,
		userId: 5,
	},
	{
		type: "spot",
		typeId: 12,
		url: "https://kblairbnb.s3.us-west-1.amazonaws.com/spot/12-5.jpg",
		previewImg: false,
		userId: 5,
	},
	{
		type: "spot",
		typeId: 12,
		url: "https://kblairbnb.s3.us-west-1.amazonaws.com/spot/12-6.jpg",
		previewImg: false,
		userId: 5,
	},

	{
		type: "spot",
		typeId: 13,
		url: "https://kblairbnb.s3.us-west-1.amazonaws.com/spot/13-0.jpg",
		previewImg: false,
		userId: 7,
	},
	{
		type: "spot",
		typeId: 13,
		url: "https://kblairbnb.s3.us-west-1.amazonaws.com/spot/13-1.jpg",
		previewImg: false,
		userId: 7,
	},
	{
		type: "spot",
		typeId: 13,
		url: "https://kblairbnb.s3.us-west-1.amazonaws.com/spot/13-2.jpg",
		previewImg: false,
		userId: 7,
	},

	{
		type: "spot",
		typeId: 14,
		url: "https://kblairbnb.s3.us-west-1.amazonaws.com/spot/14-0.jpg",
		previewImg: false,
		userId: 1,
	},
	{
		type: "spot",
		typeId: 14,
		url: "https://kblairbnb.s3.us-west-1.amazonaws.com/spot/14-1.jpg",
		previewImg: false,
		userId: 1,
	},
	{
		type: "spot",
		typeId: 14,
		url: "https://kblairbnb.s3.us-west-1.amazonaws.com/spot/14-2.jpg",
		previewImg: false,
		userId: 1,
	},

	{
		type: "spot",
		typeId: 15,
		url: "https://kblairbnb.s3.us-west-1.amazonaws.com/spot/15-0.jpg",
		previewImg: false,
		userId: 4,
	},
	{
		type: "spot",
		typeId: 15,
		url: "https://kblairbnb.s3.us-west-1.amazonaws.com/spot/15-1.jpg",
		previewImg: false,
		userId: 4,
	},
	{
		type: "spot",
		typeId: 15,
		url: "https://kblairbnb.s3.us-west-1.amazonaws.com/spot/15-2.jpg",
		previewImg: false,
		userId: 4,
	},
	{
		type: "spot",
		typeId: 15,
		url: "https://kblairbnb.s3.us-west-1.amazonaws.com/spot/15-3.jpg",
		previewImg: false,
		userId: 4,
	},

	{
		type: "spot",
		typeId: 16,
		url: "https://kblairbnb.s3.us-west-1.amazonaws.com/spot/16-0.jpg",
		previewImg: false,
		userId: 3,
	},
	{
		type: "spot",
		typeId: 16,
		url: "https://kblairbnb.s3.us-west-1.amazonaws.com/spot/16-1.jpg",
		previewImg: false,
		userId: 3,
	},
	{
		type: "spot",
		typeId: 16,
		url: "https://kblairbnb.s3.us-west-1.amazonaws.com/spot/16-2.jpg",
		previewImg: false,
		userId: 3,
	},
	{
		type: "spot",
		typeId: 16,
		url: "https://kblairbnb.s3.us-west-1.amazonaws.com/spot/16-3.jpg",
		previewImg: false,
		userId: 3,
	},

	{
		type: "spot",
		typeId: 17,
		url: "https://kblairbnb.s3.us-west-1.amazonaws.com/spot/17-0.jpg",
		previewImg: false,
		userId: 9,
	},
	{
		type: "spot",
		typeId: 17,
		url: "https://kblairbnb.s3.us-west-1.amazonaws.com/spot/17-1.jpg",
		previewImg: false,
		userId: 9,
	},
	{
		type: "spot",
		typeId: 17,
		url: "https://kblairbnb.s3.us-west-1.amazonaws.com/spot/17-2.jpg",
		previewImg: false,
		userId: 9,
	},
	{
		type: "spot",
		typeId: 17,
		url: "https://kblairbnb.s3.us-west-1.amazonaws.com/spot/17-3.jpg",
		previewImg: false,
		userId: 9,
	},
	{
		type: "spot",
		typeId: 17,
		url: "https://kblairbnb.s3.us-west-1.amazonaws.com/spot/17-4.jpg",
		previewImg: false,
		userId: 9,
	},

	{
		type: "spot",
		typeId: 18,
		url: "https://kblairbnb.s3.us-west-1.amazonaws.com/spot/18-0.jpg",
		previewImg: false,
		userId: 8,
	},
	{
		type: "spot",
		typeId: 18,
		url: "https://kblairbnb.s3.us-west-1.amazonaws.com/spot/18-1.jpg",
		previewImg: false,
		userId: 8,
	},
	{
		type: "spot",
		typeId: 18,
		url: "https://kblairbnb.s3.us-west-1.amazonaws.com/spot/18-2.jpg",
		previewImg: false,
		userId: 8,
	},
	{
		type: "spot",
		typeId: 18,
		url: "https://kblairbnb.s3.us-west-1.amazonaws.com/spot/18-3.jpg",
		previewImg: false,
		userId: 8,
	},
	{
		type: "spot",
		typeId: 18,
		url: "https://kblairbnb.s3.us-west-1.amazonaws.com/spot/18-4.jpg",
		previewImg: false,
		userId: 8,
	},
	{
		type: "spot",
		typeId: 18,
		url: "https://kblairbnb.s3.us-west-1.amazonaws.com/spot/18-5.jpg",
		previewImg: false,
		userId: 8,
	},
	{
		type: "spot",
		typeId: 18,
		url: "https://kblairbnb.s3.us-west-1.amazonaws.com/spot/18-6.jpg",
		previewImg: false,
		userId: 8,
	},

	{
		type: "spot",
		typeId: 19,
		url: "https://kblairbnb.s3.us-west-1.amazonaws.com/spot/19-0.jpg",
		previewImg: false,
		userId: 11,
	},
	{
		type: "spot",
		typeId: 19,
		url: "https://kblairbnb.s3.us-west-1.amazonaws.com/spot/19-1.jpg",
		previewImg: false,
		userId: 11,
	},
	{
		type: "spot",
		typeId: 19,
		url: "https://kblairbnb.s3.us-west-1.amazonaws.com/spot/19-2.jpg",
		previewImg: false,
		userId: 11,
	},
	{
		type: "spot",
		typeId: 19,
		url: "https://kblairbnb.s3.us-west-1.amazonaws.com/spot/19-3.jpg",
		previewImg: false,
		userId: 11,
	},
	{
		type: "spot",
		typeId: 19,
		url: "https://kblairbnb.s3.us-west-1.amazonaws.com/spot/19-4.jpg",
		previewImg: false,
		userId: 11,
	},
	{
		type: "spot",
		typeId: 19,
		url: "https://kblairbnb.s3.us-west-1.amazonaws.com/spot/19-5.jpg",
		previewImg: false,
		userId: 11,
	},
	{
		type: "spot",
		typeId: 19,
		url: "https://kblairbnb.s3.us-west-1.amazonaws.com/spot/19-6.jpg",
		previewImg: false,
		userId: 11,
	},

	{
		type: "spot",
		typeId: 20,
		url: "https://kblairbnb.s3.us-west-1.amazonaws.com/spot/20-0.jpg",
		previewImg: false,
		userId: 6,
	},
	{
		type: "spot",
		typeId: 20,
		url: "https://kblairbnb.s3.us-west-1.amazonaws.com/spot/20-1.jpg",
		previewImg: false,
		userId: 6,
	},
	{
		type: "spot",
		typeId: 20,
		url: "https://kblairbnb.s3.us-west-1.amazonaws.com/spot/20-2.jpg",
		previewImg: false,
		userId: 6,
	},
	{
		type: "spot",
		typeId: 20,
		url: "https://kblairbnb.s3.us-west-1.amazonaws.com/spot/20-3.jpg",
		previewImg: false,
		userId: 6,
	},
	{
		type: "spot",
		typeId: 20,
		url: "https://kblairbnb.s3.us-west-1.amazonaws.com/spot/20-4.jpg",
		previewImg: false,
		userId: 6,
	},
	{
		type: "spot",
		typeId: 20,
		url: "https://kblairbnb.s3.us-west-1.amazonaws.com/spot/20-5.jpg",
		previewImg: false,
		userId: 6,
	},
	{
		type: "spot",
		typeId: 20,
		url: "https://kblairbnb.s3.us-west-1.amazonaws.com/spot/20-6.jpg",
		previewImg: false,
		userId: 6,
	},
	{
		type: "spot",
		typeId: 20,
		url: "https://kblairbnb.s3.us-west-1.amazonaws.com/spot/20-7.jpg",
		previewImg: false,
		userId: 6,
	},
	{
		type: "spot",
		typeId: 20,
		url: "https://kblairbnb.s3.us-west-1.amazonaws.com/spot/20-8.jpg",
		previewImg: false,
		userId: 6,
	},

	// Images for reviews, still need to get images. previewImg defaults to false (only a function for spot images)
	{
		type: "review",
		typeId: 1,
        url: "",
        previewImg: false,
		userId: 1,
	},
	{
		type: "review",
		typeId: 2,
        url: "",
        previewImg: false,
		userId: 1,
	},
	{
		type: "review",
		typeId: 3,
        url: "",
        previewImg: false,
		userId: 1,
	},

	// images for user profile pic, still need to get images. previewImg defaults to false (only a function for spot images)
];

module.exports = { validImages };
