const validSpots = [
	{
		ownerId: 1,
		address: "1124 Oak Street",
		city: "Sunnydale",
		state: "California",
		country: "USA",
		lat: 40.7128,
		lng: -74.006,
		name: "Luxury Retreat",
        type: "house",
		description:
			"Escape to luxury in this multi-level modern masterpiece! Located in a serene suburban enclave, this high-end home redefines sophistication with its sleek lines and oblique rooftops.",
		price: 300.0,
	},
	{
		ownerId: 2,
		address: "1690 Highrise Avenue",
		city: "Metropolis",
		state: "New York",
		country: "USA",
		lat: 34.0522,
		lng: -118.2437,
		name: "Skyline View Penthouse",
        type: "house",
		description:
			"Exclusive penthouse with floor-to-ceiling windows offering stunning views of the city skyline. A glamorous choice for urban explorers.",
		price: 500.0,
	},
	{
		ownerId: 3,
		address: "789 Forest Lane",
		city: "Tranquilville",
		state: "Oregan",
		country: "USA",
		lat: 45.4215,
		lng: -122.6742,
		name: "Cozy Cottage Retreat",
        type: "house",
		description:
			"Nestled in the heart of the woods, this charming cottage offers a serene escape. Perfect for nature lovers seeking tranquility.",
		price: 150.0,
	},
	{
		ownerId: 1,
		address: "101 Mirage Drive",
		city: "Sandstone",
		state: "Arizona",
		country: "USA",
		lat: 36.1699,
		lng: -115.1398,
		name: "Desert Retreat",
        type: "house",
		description:
			"Experience the magic of the desert in this secluded oasis. Stargazing, sand dunes, and a peaceful atmosphere await.",
		price: 250.0,
	},
	{
		ownerId: 2,
		address: "112 Summit Trail",
		city: "Frostpeak",
		state: "Colorado",
		country: "USA",
		lat: 39.5501,
		lng: -105.7821,
		name: "Mountain View Cabin",
        type: "house",
		description:
			"Rustic cabin perched on a mountainside, providing breathtaking views of snow-capped peaks. Great for hikers and snow lovers.",
		price: 200.0,
	},
	{
		ownerId: 3,
		address: "893 Pine Haven",
		city: "Serenity Springs",
		state: "Washington",
		country: "USA",
		lat: 48.8566,
		lng: 2.3522,
		name: "Luxurious Log Cabin Retreat",
        type: "house",
		description:
			"Escape to the tranquility of nature in this opulent log cabin tucked away in the serene woods. This sprawling retreat boasts the rustic charm of a classic log cabin.Immerse yourself in the cozy ambiance of the stone fireplace in the grand living area, or unwind in the private sauna after a day of exploring the surrounding wilderness.",
		price: 350.0,
	},
	{
		ownerId: 1,
		address: "1237 Willow Lane",
		city: "Harmony Heights",
		state: "Texas",
		country: "USA",
		lat: 42.3601,
		lng: -71.0589,
		name: "Contemporary Suburban Home",
        type: "house",
		description:
			"Nestled in a quiet neighborhood, this sleek and spacious home offers a perfect blend of style and comfort. With multiple levels, the residence provides ample space for relaxation and entertainment. The sunlit living areas feature minimalist design, creating an inviting atmosphere for gatherings with friends and family.",
		price: 180.0,
	},
	{
		ownerId: 2,
		address: "893 Meadow View",
		city: "Rural Retreat",
		state: "Ohio",
		country: "USA",
		lat: 39.7392,
		lng: -104.9903,
		name: "Countryside Farmhouse",
        type: "house",
		description:
			"Quaint and rustic farmhouse surrounded by rolling fields and grazing animals. Ideal for a peaceful rural getaway.",
		price: 120.0,
	},
	{
		ownerId: 3,
		address: "541 Loft Street",
		city: "Cityscape",
		state: "Illinois",
		country: "USA",
		lat: 34.0522,
		lng: -118.2437,
		name: "Urban Chic Living",
        type: "house",
		description:
			" Experience urban living at its finest in this architecturally inspired haven. Immerse yourself in the sleek, modern design featuring clean lines and abundant natural light. The open layout creates an inviting atmosphere, complemented by high ceilings that add a touch of grandeur.",
		price: 280.0,
	},
	{
		ownerId: 1,
		address: "725 Concrete Avenue",
		city: "Modernville",
		state: "California",
		country: "USA",
		lat: 37.7749,
		lng: -122.4194,
		name: "Brutalist Home",
        type: "house",
		description:
			"Designed for those who appreciate the bold and the beautiful, this residence boasts striking angles, raw textures, and a unique blend of form and function. The expansive windows invite the outside world in, providing an ever-changing backdrop to your stay.",
		price: 400.0,
	},
	{
		ownerId: 2,
		address: "582 Maple Avenue",
		city: "Greenfield",
		state: "California",
		country: "USA",
		lat: 34.0522,
		lng: -118.2437,
		name: "Sunset Villa",
        type: "house",
		description:
			"Bask in the glow of the setting sun at this picturesque villa, perfect for a serene escape with its expansive views and modern amenities.",
		price: 450.0,
	},
	{
		ownerId: 5,
		address: "123 Pine Lane",
		city: "Riverdale",
		state: "Texas",
		country: "USA",
		lat: 29.7604,
		lng: -95.3698,
		name: "Riverside Mansion",
        type: "house",
		description:
			"Experience luxury by the river in this grand mansion. Enjoy the tranquil environment and state-of-the-art facilities.",
		price: 500.0,
	},
	{
		ownerId: 7,
		address: "789 Elm Street",
		city: "Hillside",
		state: "Florida",
		country: "USA",
		lat: 25.7617,
		lng: -80.1918,
		name: "Tropical Paradise",
        type: "house",
		description: "A tropical retreat with lush gardens and beautiful palm trees, perfect for a relaxing getaway.",
		price: 350.0,
	},
	{
		ownerId: 1,
		address: "456 Birch Road",
		city: "Laketown",
		state: "Nevada",
		country: "USA",
		lat: 36.1699,
		lng: -115.1398,
		name: "Lakeside Haven",
        type: "house",
		description:
			"A serene lakeside home offering peace and tranquility. Perfect for those who love water sports and relaxation.",
		price: 400.0,
	},
	{
		ownerId: 4,
		address: "321 Cedar Street",
		city: "Forestville",
		state: "Colorado",
		country: "USA",
		lat: 39.7392,
		lng: -104.9903,
		name: "Oceanfront Villa",
        type: "house",
		description:
			"A beautiful oceanfront villa offering spectacular views and modern comforts. Ideal for a seaside vacation.",
		price: 600.0,
	},
	{
		ownerId: 3,
		address: "654 Oak Avenue",
		city: "Sunnybrook",
		state: "Arizona",
		country: "USA",
		lat: 33.4484,
		lng: -112.074,
		name: "Family-Friendly Suburban Haven",
        type: "house",
		description:
			"Family-Friendly Suburban Haven provides a spacious and comfortable home in a safe, family-oriented neighborhood. Enjoy nearby playgrounds, shopping centers, and a homey atmosphere perfect for all ages.",
		price: 370.0,
	},
	{
		ownerId: 9,
		address: "789 Spruce Road",
		city: "Bayview",
		state: "Washington",
		country: "USA",
		lat: 47.6062,
		lng: -122.3321,
		name: "Bayview Escape",
        type: "house",
		description: "Enjoy stunning bay views from this luxurious home. A perfect getaway for those who love the sea.",
		price: 480.0,
	},
	{
		ownerId: 8,
		address: "321 Fir Street",
		city: "Seaside",
		state: "Oregon",
		country: "USA",
		lat: 45.5152,
		lng: -122.6784,
		name: "Mountain Retreat",
        type: "house",
		description:
			"Nestled in the mountains, this retreat offers breathtaking views and luxurious comfort. Ideal for nature lovers.",
		price: 550.0,
	},
	{
		ownerId: 11,
		address: "123 Walnut Avenue",
		city: "Hillcrest",
		state: "Georgia",
		country: "USA",
		lat: 33.749,
		lng: -84.388,
		name: "Country Estate",
        type: "house",
		description:
			"A grand estate in the countryside, offering luxury and comfort. Perfect for a peaceful and private retreat.",
		price: 430.0,
	},
	{
		ownerId: 6,
		address: "456 Chestnut Lane",
		city: "Ridgewood",
		state: "New York",
		country: "USA",
		lat: 40.7128,
		lng: -74.006,
		name: "Urban Retreat",
        type: "house",
		description:
			"A modern urban retreat in the heart of the city, offering luxurious amenities and easy access to city attractions.",
		price: 520.0,
	},
];

module.exports = {
	validSpots,
};
